package com.campione_tech.client.password_generator_ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.9
 * 2018-08-10T12:37:44.824+02:00
 * Generated source version: 2.7.9
 * 
 */
@WebServiceClient(name = "PasswordGeneratorWSServerService", 
                  wsdlLocation = "http://localhost:8081/password_generator_ws/services/PasswordGeneratorWSServerPort?wsdl",
                  targetNamespace = "http://password_generator_ws.ws.campione_tech.com/") 
public class PasswordGeneratorWSServerService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://password_generator_ws.ws.campione_tech.com/", "PasswordGeneratorWSServerService");
    public final static QName PasswordGeneratorWSServerPort = new QName("http://password_generator_ws.ws.campione_tech.com/", "PasswordGeneratorWSServerPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8081/password_generator_ws/services/PasswordGeneratorWSServerPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PasswordGeneratorWSServerService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8081/password_generator_ws/services/PasswordGeneratorWSServerPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PasswordGeneratorWSServerService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PasswordGeneratorWSServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PasswordGeneratorWSServerService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PasswordGeneratorWSServerService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PasswordGeneratorWSServerService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PasswordGeneratorWSServerService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns PasswordGeneratorWSServer
     */
    @WebEndpoint(name = "PasswordGeneratorWSServerPort")
    public PasswordGeneratorWSServer getPasswordGeneratorWSServerPort() {
        return super.getPort(PasswordGeneratorWSServerPort, PasswordGeneratorWSServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PasswordGeneratorWSServer
     */
    @WebEndpoint(name = "PasswordGeneratorWSServerPort")
    public PasswordGeneratorWSServer getPasswordGeneratorWSServerPort(WebServiceFeature... features) {
        return super.getPort(PasswordGeneratorWSServerPort, PasswordGeneratorWSServer.class, features);
    }

}
