
package com.campione_tech.client.password_generator_ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.7.9
 * 2018-08-10T12:37:44.710+02:00
 * Generated source version: 2.7.9
 * 
 */
public final class PasswordGeneratorWSServer_PasswordGeneratorWSServerPort_Client {

    private static final QName SERVICE_NAME = new QName("http://password_generator_ws.ws.campione_tech.com/",
            "PasswordGeneratorWSServerService");

    private PasswordGeneratorWSServer_PasswordGeneratorWSServerPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = PasswordGeneratorWSServerService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        PasswordGeneratorWSServerService ss = new PasswordGeneratorWSServerService(wsdlURL, SERVICE_NAME);
        PasswordGeneratorWSServer port = ss.getPasswordGeneratorWSServerPort();

        {
            System.out.println("Invoking generatePassword...");
            java.lang.String _generatePassword_length = "14";
            java.lang.String _generatePassword__return = port.generatePassword(_generatePassword_length);
            System.out.println("generatePassword.result=" + _generatePassword__return);

        }
        {
            System.out.println("Invoking version...");
            java.lang.String _version__return = port.version();
            System.out.println("version.result=" + _version__return);

        }

        System.exit(0);
    }

}
