
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.campione_tech.client.password_generator_ws;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.9
 * 2018-08-10T12:37:44.787+02:00
 * Generated source version: 2.7.9
 * 
 */

@javax.jws.WebService(
                      serviceName = "PasswordGeneratorWSServerService",
                      portName = "PasswordGeneratorWSServerPort",
                      targetNamespace = "http://password_generator_ws.ws.campione_tech.com/",
                      wsdlLocation = "http://localhost:8081/password_generator_ws/services/PasswordGeneratorWSServerPort?wsdl",
                      endpointInterface = "com.campione_tech.client.password_generator_ws.PasswordGeneratorWSServer")
                      
public class PasswordGeneratorWSServerImpl implements PasswordGeneratorWSServer {

    private static final Logger LOG = Logger.getLogger(PasswordGeneratorWSServerImpl.class.getName());

    /* (non-Javadoc)
     * @see com.campione_tech.client.password_generator_ws.PasswordGeneratorWSServer#generatePassword(java.lang.String  length )*
     */
    public java.lang.String generatePassword(java.lang.String length) { 
        LOG.info("Executing operation generatePassword");
        System.out.println(length);
        try {
            java.lang.String _return = "_return-1813706506";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.campione_tech.client.password_generator_ws.PasswordGeneratorWSServer#version(*
     */
    public java.lang.String version() { 
        LOG.info("Executing operation version");
        try {
            java.lang.String _return = "_return-1304398976";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
