package com.campione_tech.client.password_generator_ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.9
 * 2018-08-10T12:37:44.807+02:00
 * Generated source version: 2.7.9
 * 
 */
@WebService(targetNamespace = "http://password_generator_ws.ws.campione_tech.com/", name = "PasswordGeneratorWSServer")
@XmlSeeAlso({ObjectFactory.class})
public interface PasswordGeneratorWSServer {

    @WebMethod(action = "urn:GeneratePasswordAction")
    @RequestWrapper(localName = "generatePassword", targetNamespace = "http://password_generator_ws.ws.campione_tech.com/", className = "com.campione_tech.client.password_generator_ws.GeneratePassword")
    @ResponseWrapper(localName = "generatePasswordResponse", targetNamespace = "http://password_generator_ws.ws.campione_tech.com/", className = "com.campione_tech.client.password_generator_ws.GeneratePasswordResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String generatePassword(
        @WebParam(name = "length", targetNamespace = "")
        java.lang.String length
    );

    @WebMethod(action = "urn:VersionAction")
    @RequestWrapper(localName = "version", targetNamespace = "http://password_generator_ws.ws.campione_tech.com/", className = "com.campione_tech.client.password_generator_ws.Version")
    @ResponseWrapper(localName = "versionResponse", targetNamespace = "http://password_generator_ws.ws.campione_tech.com/", className = "com.campione_tech.client.password_generator_ws.VersionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String version();
}
