
package com.campione_tech.ws.password_generator_ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.9
 * Fri Aug 10 10:58:42 CEST 2018
 * Generated source version: 2.7.9
 */

@XmlRootElement(name = "version", namespace = "http://password_generator_ws.ws.campione_tech.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "version", namespace = "http://password_generator_ws.ws.campione_tech.com/")

public class Version {


}

