<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="PasswordGeneratorWSServerService" targetNamespace="http://password_generator_ws.ws.campione_tech.com/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://password_generator_ws.ws.campione_tech.com/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
  <import namespace="http://password_generator_ws.ws.campione_tech.com/" schemaLocation="passwordgeneratorwsserver_schema1.xsd"/>
</schema>
  </wsdl:types>
  <wsdl:message name="generatePassword">
    <wsdl:part name="parameters" element="tns:generatePassword">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="version">
    <wsdl:part name="parameters" element="tns:version">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="versionResponse">
    <wsdl:part name="parameters" element="tns:versionResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="generatePasswordResponse">
    <wsdl:part name="parameters" element="tns:generatePasswordResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="PasswordGeneratorWSServer">
    <wsdl:operation name="generatePassword">
      <wsdl:input name="generatePassword" message="tns:generatePassword">
    </wsdl:input>
      <wsdl:output name="generatePasswordResponse" message="tns:generatePasswordResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="version">
      <wsdl:input name="version" message="tns:version">
    </wsdl:input>
      <wsdl:output name="versionResponse" message="tns:versionResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="PasswordGeneratorWSServerServiceSoapBinding" type="tns:PasswordGeneratorWSServer">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="generatePassword">
      <soap:operation soapAction="urn:GeneratePasswordAction" style="document"/>
      <wsdl:input name="generatePassword">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="generatePasswordResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="version">
      <soap:operation soapAction="urn:VersionAction" style="document"/>
      <wsdl:input name="version">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="versionResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="PasswordGeneratorWSServerService">
    <wsdl:port name="PasswordGeneratorWSServerPort" binding="tns:PasswordGeneratorWSServerServiceSoapBinding">
      <soap:address location="http://localhost:8081/password_generator_ws/services/PasswordGeneratorWSServerPort"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
